# Generated by Django 4.2.5 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
