# Generated by Django 4.2.5 on 2024-08-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_archived',
        ),
    ]
