# Generated by Django 4.2.5 on 2024-08-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalunit',
            old_name='serials',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='serials',
            new_name='serial',
        ),
    ]
