# Generated by Django 4.2.5 on 2024-06-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
