# Generated by Django 4.2.5 on 2024-06-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuffs.category'),
        ),
    ]
