# Generated by Django 4.2.5 on 2024-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_rename_serials_historicalunit_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='barcode',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='barcode',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
