# Generated by Django 4.2.5 on 2024-09-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_itemstatus_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_status', to='stuffs.item'),
        ),
    ]
