# Generated by Django 4.2.5 on 2024-08-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0003_historicalunit_barcode_unit_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunit',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='barcode',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
