# Generated by Django 4.2.5 on 2024-06-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0003_unit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stuffs.unitkit'),
        ),
    ]
