# Generated by Django 4.2.5 on 2024-09-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0004_historicalunit_unit_status_unit_unit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_status', to='stuffs.unitstatus'),
        ),
    ]
