# Generated by Django 4.2.5 on 2024-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0004_alter_historicalunit_barcode_alter_unit_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunitkit',
            name='kit_code',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='unitkit',
            name='kit_code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
