# Generated by Django 4.2.5 on 2024-09-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0005_alter_unit_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunit',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='create_by',
        ),
    ]
