# Generated by Django 4.2.5 on 2024-06-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0005_historicalunitkit_historicalunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunit',
            name='model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
