# Generated by Django 4.2.5 on 2024-09-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0006_remove_historicalunit_create_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='stuffs.unitkit'),
        ),
    ]
