# Generated by Django 4.2.5 on 2024-06-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0006_alter_historicalunit_model_alter_unit_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'unit statuses',
            },
        ),
    ]
