# Generated by Django 4.2.5 on 2024-08-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0006_kitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitassignment',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
