# Generated by Django 4.2.5 on 2024-09-11 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuffs', '0007_alter_unit_unit_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitassignment',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitassignment',
            name='unit_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_assignments', to='stuffs.unitkit'),
        ),
    ]
