# Generated by Django 4.2.5 on 2024-08-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0007_kitassignment_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunitkit',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='unitkit',
            name='assign_to',
        ),
    ]
