# Generated by Django 4.2.5 on 2024-06-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0007_unitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='item_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stuffs.unitstatus'),
        ),
        migrations.AddField(
            model_name='unit',
            name='item_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stuffs.unitstatus'),
        ),
    ]
