# Generated by Django 4.2.5 on 2024-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0008_remove_historicalunitkit_assign_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunitkit',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitkit',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
