# Generated by Django 4.2.5 on 2024-09-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0009_alter_unit_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunit',
            name='unit_status',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_status',
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=120, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_status', to='stuffs.item')),
                ('unit_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_status', to='stuffs.unitstatus')),
            ],
        ),
    ]
