# Generated by Django 4.2.5 on 2024-08-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0010_alter_historicalunitkit_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
