# Generated by Django 4.2.5 on 2024-09-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0010_remove_historicalunit_unit_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalKitAssignment',
        ),
    ]
