# Generated by Django 4.2.5 on 2024-09-20 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuffs', '0011_delete_historicalkitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatus',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
