# Generated by Django 4.2.5 on 2024-09-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0011_historicalunit_descriptions_unit_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitassignment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
